[manager]

append_keymap = [
       { on = [ "g", "n" ], run = "cd ~/Gdrive/Uni/Notes/", desc = "Go to Notes" },
       { on = [ "g", "a" ], run = "cd ~/Gdrive/Uni/Assignments/", desc = "Go to Assignments" },
]
